#Development Docker Compose
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/ChefCompanion
      dockerfile: Dockerfile
      target: development
    container_name: frontend
    volumes:
      - ./frontend/ChefCompanion/src:/frontend/src
      - ./frontend/ChefCompanion/public:/frontend/public
      - ./frontend/ChefCompanion/dist:/frontend/dist
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: backend
    environment:
        DATABASE_PORT: 5432
        DATABASE_HOST: database
        DATABASE_NAME: chefCompanionDB
        DATABASE_USER: chef
        DATABASE_PASSWORD: chef
        DJANGO_DEBUG: True
    volumes:
      - ./backend:/backend
    ports:
      - '8000:8000'
    depends_on:
      - database

  database:
    image: postgres:16
    container_name: database
    environment:
        POSTGRES_DB: chefCompanionDB
        POSTGRES_USER: chef 
        POSTGRES_PASSWORD: chef 
    volumes:
      - ./database:/database
    ports:
      - '5432:5432'