# Generated by Django 4.2.6 on 2023-10-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=1024)),
                ('directions', models.CharField(max_length=1024)),
                ('link', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('ner', models.CharField(db_column='NER', max_length=255)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
    ]
