# Generated by Django 4.2.6 on 2023-10-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefCompanionAPI', '0002_alter_recipes_ner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientlist',
            name='amount',
            field=models.CharField(default='insert amount', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='experationDate',
            field=models.CharField(default='insert date', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='name',
            field=models.CharField(default='insert name', max_length=255),
        ),
    ]
