name: Eslint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/ChefCompanion
    - run: npm install eslint && npm install eslint-plugin-react
      working-directory: ./frontend/ChefCompanion
    - run: npx eslint . --ext .jsx --max-warnings=0
      working-directory: ./frontend/ChefCompanion/src
